version: "3.3"

services:
  app:
    container_name: amtech-mltb
    build:
      context: .
      dockerfile: Dockerfile
    command: bash start.sh
    restart: on-failure
    ports:
      - "83:83"
    
